import type { CommunityWork } from "./types";

// ponytail: static seed. Swap for a services/ API call to the public feed later.
export const COMMUNITY_WORKS: CommunityWork[] = [
  {
    id: "last-delivery",
    title: "The Last Delivery | COURIER AI Commercial",
    author: "rajnert_piotr",
    duration: "1:03",
    timeAgo: "2 weeks ago",
    gradient: "linear-gradient(135deg,#b45309,#78350f 60%,#1c1917)",
    likes: 6,
    bookmarks: 2,
    comments: 8,
  },
  {
    id: "poland-2099",
    title: "POLAND 2099",
    author: "rajnert_piotr",
    duration: "10:51",
    timeAgo: "4 weeks ago",
    gradient: "linear-gradient(135deg,#a8a29e,#57534e 60%,#292524)",
    likes: 14,
    bookmarks: 7,
    comments: 18,
  },
  {
    id: "mahabharata",
    title: "MAHABHARATA | The Greatest Story Ever Told",
    author: "Amalvfx",
    duration: "2:51",
    timeAgo: "2 weeks ago",
    gradient: "linear-gradient(135deg,#475569,#1e293b 60%,#0f172a)",
    likes: 6,
    bookmarks: 2,
    comments: 4,
  },
  {
    id: "atlantis",
    title: "ATLANTIS: Deep Signal",
    author: "marina_light",
    duration: "11:10",
    timeAgo: "1 week ago",
    gradient: "linear-gradient(135deg,#0e7490,#155e75 60%,#083344)",
    likes: 7,
    bookmarks: 3,
    comments: 0,
    badge: "Short Film · Episode 3 of 4",
  },
  {
    id: "verdant",
    title: "Verdant | A Forest Study",
    author: "marina_light",
    duration: "9:09",
    timeAgo: "3 days ago",
    gradient: "linear-gradient(135deg,#3f6212,#1a2e05 60%,#0c0a09)",
    likes: 2,
    bookmarks: 0,
    comments: 9,
  },
  {
    id: "the-siege",
    title: "The Siege of Ember Hall",
    author: "Amalvfx",
    duration: "11:39",
    timeAgo: "5 days ago",
    gradient: "linear-gradient(135deg,#9a3412,#7c2d12 60%,#1c1917)",
    likes: 3,
    bookmarks: 1,
    comments: 2,
  },
];
