"""workspace plan

Revision ID: 32ffe0b9b9ae
Revises: 6d4b99bc9be1
Create Date: 2026-07-21 15:02:21.676469
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "32ffe0b9b9ae"
down_revision: str | None = "6d4b99bc9be1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspace",
        sa.Column(
            "plan", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="free"
        ),
    )
    op.alter_column("workspace", "plan", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace", "plan")
    # ### end Alembic commands ###
