"""asset storage key and node index

Revision ID: 3b4acf7112b9
Revises: 43c2af16c5c9
Create Date: 2026-07-21 03:04:40.820372
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "3b4acf7112b9"
down_revision: str | None = "43c2af16c5c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "asset",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""),
    )
    op.alter_column("asset", "key", server_default=None)
    op.create_index(op.f("ix_asset_node_id"), "asset", ["node_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_asset_node_id"), table_name="asset")
    op.drop_column("asset", "key")
    # ### end Alembic commands ###
