"""user oauth fields

Revision ID: 43c2af16c5c9
Revises: 5a6423783e7d
Create Date: 2026-07-21 00:48:43.463639
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '43c2af16c5c9'
down_revision: str | None = '5a6423783e7d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Backfill existing rows with the default, then drop the server default so
    # the column matches the model (Python-side default only).
    op.add_column(
        'users',
        sa.Column(
            'auth_provider',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='password',
        ),
    )
    op.alter_column('users', 'auth_provider', server_default=None)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
