"""billing credits and usage

Revision ID: 5a6423783e7d
Revises: 48850c1394fc
Create Date: 2026-07-21 00:37:09.745652
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '5a6423783e7d'
down_revision: str | None = '48850c1394fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_workspace_id'), 'credit', ['workspace_id'], unique=True)
    op.create_table('usage_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_record_execution_id'), 'usage_record', ['execution_id'], unique=False)
    op.create_index(op.f('ix_usage_record_workspace_id'), 'usage_record', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_record_workspace_id'), table_name='usage_record')
    op.drop_index(op.f('ix_usage_record_execution_id'), table_name='usage_record')
    op.drop_table('usage_record')
    op.drop_index(op.f('ix_credit_workspace_id'), table_name='credit')
    op.drop_table('credit')
    # ### end Alembic commands ###
