"""usage_record provider usd

Revision ID: 6d4b99bc9be1
Revises: 3b4acf7112b9
Create Date: 2026-07-21 14:19:59.345525
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6d4b99bc9be1"
down_revision: str | None = "3b4acf7112b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usage_record", sa.Column("usd", sa.Float(), nullable=False, server_default="0"))
    op.alter_column("usage_record", "usd", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_record", "usd")
    # ### end Alembic commands ###
